name: Build Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Pre-install some dependencies
        run: |
          echo "<settings><servers><server><id>github</id><username>khwj</username><password>\${env.GITHUB_TOKEN}</password></server></servers></settings>" > settings.xml
          mvn dependency:get -DremoteRepositories=https://public.nexus.pentaho.org/content/groups/omni/ -Dartifact=org.pentaho:pentaho-aggdesigner-algorithm:5.1.5-jhyde:jar
          mvn dependency:get -DremoteRepositories=github::::https://maven.pkg.github.com/khwj/hive -Dartifact=org.spark-project.hive:hive-exec:2.3.7:jar
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify